### PR TITLE
More flexible strides

### PR DESCRIPTION
**Pull request by ftynse**
~~Subsumes #3, do not merge until that.~~

Closes #2 (different implementation solving the problem)

### CODE REVIEW

**Comment by chelini** [comment]
I have just few questions. In the function ```mapToNext```  you allow multiple dimensions, but the input is just a single dimension map. Do you plan to change to multiple dimension maps? The second question is the following: in case of ```nonEmptySchedulePoints``` after computing the lexmin you apply range and domain. This does not introduce anything but it is just to handle the other case, am I correct?

**Comment by chelini** [comment]
Do you want me also to add few test cases?

**Comment by ftynse** [comment]
On 11/09/2018 17:26, lorenzo chelini wrote:
>
> I have just few questions. In the function |mapToNext| you allow 
> multiple dimensions, but the input is just a single dimension map. Do 
> you plan to change to multiple dimension maps?
>

It's not necessarily a map in a single-dimensional space, just the test 
case we have is single-dimensional.  The map-to-next set is constructed 
in the schedule space, which becomes multidimensional as soon as you 
generate nested loops

> The second question is the following: in case of 
> |nonEmptySchedulePoints| after computing the lexmin you apply range 
> and domain. This does not introduce anything but it is just to handle 
> the other case, am I correct?
>

Note sure I follow you.  If you want, you can switch to "changes" tab, 
click on the line you find suspicious and write a comment directly to it.
First, I call the mapToNext function that may return a map from a point 
in schedule space to either the next (+1 in the last dim) point, or to 
all following points (> in the last dim) depending on whether 
nonEmptySchedulePoints is null.
Then, if nonEmptySchedulePoints are provided, I use intersections and 
lexmin to restrict the relation to only contain the single point on the 
right instead of all following points.
Immediately after the branch, I must have a one-to-one map in all cases.
Given that map, I keep applying the (partial) scheduled access map to 
get the relation between elements accessed at the given points in 
schedule space, rather than between the points in schedule space.

It may me easy to look commit-by-commit, you are interested in 
aa886b11667a31df3bd6974d17d2e5c4557c6608 in this case.
As you may see, it only modifies how the map in schedule space is 
constructed, everything else remains as it was.

**Comment by ftynse** [comment]
On 11/09/2018 17:27, lorenzo chelini wrote:
>
> Do you want me also to add few test cases?
>

Sure, if you think it is necessary.

**Review by chelini — APPROVED** [review]

**Comment by chelini** [comment]
Thanks for the answer not it is clear.

**Pull request merged**
