### PR TITLE
include Google Test as a submodule

### PR DESCRIPTION
**Pull request by ftynse**
Rather then downloading/updating Google Test on each call to cmake, introduce
it as a submodule and build accordingly.

Pros:
 - no hidden dependency;
 - our project can be compiled offline;
 - build scripts are arguably simpler.

Cons:
 - necessity to manually bump the submodule;
 - ~~applying local patches to gtest is messy.~~

~~The latter point can be addressed by (1) submitting a patch to googletest; or
(2) rewriting the patch application mechanism in cmake so that it operates at
configuration time.~~

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
This LGTM.

**Review by pfaffe — COMMENTED** [review]
Is it truly necessary to apply patches? In that case it might be more appropriate to use a git subtree instead of a submodule.

Subtrees require some commit discipline to keep commits for the subtree and the root isolated, but it makes tracking local patches easier, in my opinion. A gtest update is then just a git subtree pull (involving the occasional merge conflicts with the local patches).

**Comment by ftynse** [comment]
We also apply patches to isl, so I think it's better to be consistent.

The gtest patch was originally introduced by @tobig , I don't seem to have a problem with `-Wmisleading-indentation` using gcc-7.3.0.  Maybe the problem has been fixed upstream already and we can just drop the patch and the clutches that apply it altogether.

**Comment by ftynse** [comment]
>  Maybe the problem has been fixed upstream already and we can just drop the patch and the clutches that apply it altogether.

It looks like it is indeed the case https://github.com/google/googletest/pull/1820

**Comment by tobiasgrosser** [comment]
Nice. This means we can drop the patch. Even better.

**Pull request merged**
